name: AI Stock Check

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 最新版

      - name: Set up Python
        uses: actions/setup-python@v5 # 最新版
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install yfinance requests google-generativeai pandas

      - name: Run script
        env:
          # ここはGitHubのSettingsで登録した名前と一致させてください
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python sbi_ai_bot.py
